use olc::Pixel;
use olc_pixel_game_engine as olc;
pub const COLORS: [Pixel; 16] = [
    Pixel::rgb(0x00, 0x00, 0x00),
    Pixel::rgb(0x00, 0x00, 0xAA),
    Pixel::rgb(0x00, 0xAA, 0x00),
    Pixel::rgb(0x00, 0xAA, 0xAA),
    Pixel::rgb(0xAA, 0x00, 0x00),
    Pixel::rgb(0xAA, 0x00, 0xAA),
    Pixel::rgb(0xAA, 0x55, 0x00),
    Pixel::rgb(0xAA, 0xAA, 0xAA),
    Pixel::rgb(0x55, 0x55, 0x55),
    Pixel::rgb(0x55, 0x55, 0xFF),
    Pixel::rgb(0x55, 0xFF, 0x55),
    Pixel::rgb(0x55, 0xFF, 0xFF),
    Pixel::rgb(0xFF, 0x55, 0x55),
    Pixel::rgb(0xFF, 0x55, 0xFF),
    Pixel::rgb(0xFF, 0xFF, 0x00),
    Pixel::rgb(0xFF, 0xFF, 0xFF),
];

pub const KEYS: [olc::Key; 0x55] = [
    olc::Key::NONE,
    olc::Key::A,
    olc::Key::B,
    olc::Key::C,
    olc::Key::D,
    olc::Key::E,
    olc::Key::F,
    olc::Key::G,
    olc::Key::H,
    olc::Key::I,
    olc::Key::J,
    olc::Key::K,
    olc::Key::L,
    olc::Key::M,
    olc::Key::N,
    olc::Key::O,
    olc::Key::P,
    olc::Key::Q,
    olc::Key::R,
    olc::Key::S,
    olc::Key::T,
    olc::Key::U,
    olc::Key::V,
    olc::Key::W,
    olc::Key::X,
    olc::Key::Y,
    olc::Key::Z,
    olc::Key::K0,
    olc::Key::K1,
    olc::Key::K2,
    olc::Key::K3,
    olc::Key::K4,
    olc::Key::K5,
    olc::Key::K6,
    olc::Key::K7,
    olc::Key::K8,
    olc::Key::K9,
    olc::Key::F1,
    olc::Key::F2,
    olc::Key::F3,
    olc::Key::F4,
    olc::Key::F5,
    olc::Key::F6,
    olc::Key::F7,
    olc::Key::F8,
    olc::Key::F9,
    olc::Key::F10,
    olc::Key::F11,
    olc::Key::F12,
    olc::Key::UP,
    olc::Key::DOWN,
    olc::Key::LEFT,
    olc::Key::RIGHT,
    olc::Key::SPACE,
    olc::Key::TAB,
    olc::Key::SHIFT,
    olc::Key::CTRL,
    olc::Key::INS,
    olc::Key::DEL,
    olc::Key::HOME,
    olc::Key::END,
    olc::Key::PGUP,
    olc::Key::PGDN,
    olc::Key::BACK,
    olc::Key::ESCAPE,
    olc::Key::RETURN,
    olc::Key::ENTER,
    olc::Key::PAUSE,
    olc::Key::SCROLL,
    olc::Key::NP0,
    olc::Key::NP1,
    olc::Key::NP2,
    olc::Key::NP3,
    olc::Key::NP4,
    olc::Key::NP5,
    olc::Key::NP6,
    olc::Key::NP7,
    olc::Key::NP8,
    olc::Key::NP9,
    olc::Key::NP_MUL,
    olc::Key::NP_DIV,
    olc::Key::NP_ADD,
    olc::Key::NP_SUB,
    olc::Key::NP_DECIMAL,
    olc::Key::PERIOD,
];
